"""Adding Event Type table

Revision ID: 15956e35ee96
Revises: e2c3937c6879
Create Date: 2022-11-02 06:19:01.594993

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '15956e35ee96'
down_revision = 'e2c3937c6879'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # MANUAL: data migration into eventtype table
    eventtype_table = op.create_table('eventtype',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.bulk_insert(eventtype_table,
        [
            {'id': 1, 'name': 'yardsale', 'display_name': 'Yard Sale', 'is_active': True},
            {'id': 2, 'name': 'halloween', 'display_name': 'Halloween', 'is_active': False},
            {'id': 3, 'name': 'lemonade', 'display_name': 'Lemonade Stand', 'is_active': True},
        ]
    )

    # MANUAL: making sure nullable=False works
    op.add_column('yardsale', sa.Column('event_type_id', sa.Integer(), nullable=True))
    op.execute("UPDATE yardsale SET event_type_id = 1")
    op.alter_column('yardsale', 'event_type_id', nullable=False)
    # op.add_column('yardsale', sa.Column('event_type_id', sa.Integer(), nullable=False))
    # MANUAL: None -> 'fk_event_type_id_id
    op.create_foreign_key('fk_event_type_id_id', 'yardsale', 'eventtype', ['event_type_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # MANUAL: None -> 'fk_event_type_id_id
    op.drop_constraint('fk_event_type_id_id', 'yardsale', type_='foreignkey')
    op.drop_column('yardsale', 'event_type_id')
    op.drop_table('eventtype')
    # ### end Alembic commands ###
